### ISSUE TITLE
Make it easier to find repo from youtube talk

### ISSUE THREAD

**Issue by FullstackSensei** [arduano/jit-demo#1]
Hi,
The Algorithm™ suggested your Rust JIT Demo talk. Really awesome talk and work!

Unfortunately, the talk doesn't link to your repo, and the video doesn't have a clear screenshot of your repo. It took a lot of googling and searching on github to find this repo.

It would really help if you could contact the event organizers to ask them to link to this repo. In the meantime, it would also help to somehow add a short description that mentions the talk's title and maybe link to it in the about of this repo, to make it easier to search for.
Thanks!

**Comment by arduano** [comment]
Will do lol, will close this for now, it should be added very soon

**Comment by pinkforest** [comment]
fixed few days ago
